version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install -DskipTests=true
      - store_artifacts:
          path: target/
  test:
    docker:
      - image: maven:3.6.3-jdk-11
    steps:
      - checkout
      - run:
          name: Build and test with Maven
          command: mvn clean test
  deploy: 
    docker:
      - image: maven:3.6.3-jdk-11
    steps: 
      - run: echo "StudentUI is ready for deployment for prod"


workflows:
  version: 2
  build-and-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
